Scriptname SeverActions_Follow extends Quest
{Follow system. Both modes ride the 200-alias follow pool + a LinkedRef:
 casual follow (StartFollowing/StopFollowing: guards, random NPCs, no roster
 entry) and companion follow (CompanionStartFollowing/CompanionStopFollowing:
 SetCompanion recruits, plus roster, relationships and schedules). Casual vs
 companion is the ROSTER (Native_GetIsFollower), never the follow mechanism.
 Legacy SkyrimNet-driven casuals migrate to the pool in the load sweep.}

; =============================================================================
; PROPERTIES
; =============================================================================

int Property FollowPackagePriority = 50 AutoReadOnly
{Priority of a SkyrimNet FollowPlayer registration (legacy casuals only).
Kept low so it doesn't overtake other mods' packages; the pool's alias
packages don't use it.}

ReferenceAlias[] Property FollowerSlots Auto
{Legacy: 21 CK alias slots carrying SeverActions_FollowPlayerPackage.
Superseded by the 200-alias pool (FLWD v18): a held slot is a transitional
state to strip, filled only on an ESP that predates the pool.}

; ── 200-alias follow pool (FLWD v18) ──
; Every follower rides an alias of SeverActions_FollowQuest, whose CK packages
; (Close above V2) re-apply natively on cell load; PO3 overrides drop on 3D
; unload and nothing re-heals them mid-session. The override pair survives
; only as the >200 fallback.
Int Property FOLLOW_QUEST_FORMID    = 0x0016A78D AutoReadOnly
{SeverActions_FollowQuest — 200-slot ReferenceAlias pool (Follower_000..199),
 each carrying SeverActions_FollowPlayerClose above SeverActions_FollowPlayerPackageV2.
 Generated by xEdit Scripts/GenerateFollowQuest.pas.}
Int Property FOLLOW_ALIAS_POOL_SIZE = 200 AutoReadOnly

; ── Camp persistence pool ──
; SeverActions_CampPersist: 300 package-free aliases keeping sworn camp members
; persistent (resolvable anywhere, immune to the leveled-actor re-roll).
Int Property CAMP_PERSIST_QUEST_FORMID = 0x16A793 AutoReadOnly
Int Property CAMP_PERSIST_POOL_SIZE = 300 AutoReadOnly

; ── Retainer persistence pool ──
; SeverActions_RetainerPersist: 500 package-free aliases keeping every active
; retainer persistent (native seats them, VentureMonitor::SeatInPersistPool).
Int Property RETAINER_PERSIST_QUEST_FORMID = 0x16B000 AutoReadOnly
Int Property RETAINER_PERSIST_POOL_SIZE = 500 AutoReadOnly
; Both pools and the camp muster are SeverActions_Enterprises' since P9-03. These
; four constants and the seven _campPersist* / _retainerPersist* variables below
; are unused here but stay: an old suspended frame's saved bytecode names them (F7).
Quest _followQuest = None
Bool _followQuestResolved = false
Quest _campPersistQuest = None
Bool _campPersistResolved = false
Bool _campPersistMissingWarned = false
Int _campPersistCursor = 0
Quest _retainerPersistQuest = None
Bool _retainerPersistResolved = false
Bool _retainerPersistMissingWarned = false

Keyword Property SeverActions_FollowerFollowKW Auto
{SA's follow LinkedRef: on a follower SA leads, pointing at the player. No
package reads it (the follow packages target the player directly); only the
orphan scanner's follow check keys on it. SA clears it when it releases them, a
rostered follower's by the next load at the latest.}

Faction Property SeverActions_ActivelyFollowing Auto
{Held while a follower actively follows; removed on wait, sandbox, stop or
dismiss. A prompt tag (SkyrimNet's target selector lets engaged companions
speak more readily), not a state source - see HasFollowPackage.}

Faction Property SeverActions_WaitingFaction Auto
{Held while an NPC is told to wait. Interop signal: other mods (IntelEngine)
read it to leave waiting NPCs alone. Remove with ClearWaitingFaction.}

Package Property SandboxPackage Auto
{Manual sandbox package (wait/sandbox action) for relaxing in place — NPC wanders
and interacts with nearby furniture.}

Package Property SafeInteriorSandboxPackage Auto
{Package for the AUTO safe-interior sandbox (inns, homes...), distinct from
SandboxPackage so the two flows can be told apart. Falls back to
SandboxPackage when unset.}

int Property SandboxPackagePriority = 100 AutoReadOnly
{100 (Hearth's camp sandbox uses the same) wins against typical
 follower-framework overrides. It is added before FollowPlayer is cleared
 (SkyrimNet's UnregisterPackage is async), and every exit path
 (StopSandbox, OnNativeSandboxCleanup, StartFollowing,
 CompanionStartFollowing) removes it explicitly.}

int Property SafeInteriorSandboxPriority = 100 AutoReadOnly
{Same priority as regular sandbox — overrides follow package.}

; =============================================================================
; INIT
; =============================================================================

Event OnInit()
    Debug.Trace("[SeverActions_Follow] Initialized")
    RegisterForModEvent("SeverActionsNative_SandboxCleanup", "OnNativeSandboxCleanup")
    RegisterForModEvent("SeverActions_SafeInteriorReEval", "OnSafeInteriorReEval")
    RegisterForModEvent("SeverActions_SafeInteriorReassert", "OnSafeInteriorReassert")
    RegisterForModEvent("SeverActions_SafeInteriorRelease", "OnSafeInteriorRelease")
    RegisterForModEvent("SeverActions_CasualFollowRecycle", "OnCasualFollowRecycle")
EndEvent

; The auto safe-interior package (see SafeInteriorSandboxPackage).
Package Function GetSafeInteriorPackage()
    If SafeInteriorSandboxPackage
        Return SafeInteriorSandboxPackage
    EndIf
    Return SandboxPackage
EndFunction

; ── Wait In Place (Settings > Followers > Movement) ──
; A manual wait uses SandboxPackage (LeisureSandbox 0BDDFF, r1200: they mill
; around). Wait In Place swaps in SeverActions_WaitPackage 05DA58, a HOLD
; POSITION at package start, r0 (vanilla's own wait); a Sandbox at r0 still
; shuffles. It must be an override: SA's follow packages have no wait branch and
; gate on WaitingForPlayer == 0, so the flag alone drops them to base AI. The
; record's location TYPE must stay NEAR PACKAGE START (xEdit
; Scripts/FixWaitPackage.pas). Resolved by FormID: runtime EditorIDs are
; stripped without po3 Tweaks (none on VR).
Int Property WAIT_IN_PLACE_PKG_FORMID = 0x05DA58 AutoReadOnly
Package _waitInPlacePkg = None       ; lazy cache
Bool _waitInPlacePkgWarned = False

Package Function ResolveWaitInPlacePackage()
    {05DA58, cached after the first resolve (it runs inside teardown loops).
     Logs once on failure: callers fall back to the wide package, and a
     silent fallback would hide a broken ESP record.}
    If !_waitInPlacePkg
        _waitInPlacePkg = Game.GetFormFromFile(WAIT_IN_PLACE_PKG_FORMID, "SeverActions.esp") as Package
        If !_waitInPlacePkg && !_waitInPlacePkgWarned
            _waitInPlacePkgWarned = True
            Debug.Trace("[SeverActions_Follow] WARNING: SeverActions_WaitPackage 0x05DA58 did not resolve - Wait In Place falls back to the 1200u LeisureSandbox")
        EndIf
    EndIf
    Return _waitInPlacePkg
EndFunction

Package Function GetWaitSandboxPackage()
    {The package a MANUAL wait applies: the wide LeisureSandbox, or the r0
     hold with Wait In Place on. Any failure falls back to the wide package,
     so a waiting follower always has one.}
    SeverActions_FollowerManager fmWaitPk = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
    If !fmWaitPk || !SeverActionsNativeExt2.Settings_GetBool("waitInPlace")
        Return SandboxPackage
    EndIf
    Package tightPkg = ResolveWaitInPlacePackage()
    If tightPkg
        Return tightPkg
    EndIf
    Return SandboxPackage
EndFunction

Function RemoveWaitSandboxPackages(Actor akActor)
    {Strip BOTH manual-wait packages: the toggle can flip mid-wait, and the
     one the current setting doesn't name would stay a live priority-100
     override. Removing a package the actor never had is a no-op.}
    If !akActor
        Return
    EndIf
    If SandboxPackage
        ActorUtil.RemovePackageOverride(akActor, SandboxPackage)
    EndIf
    Package tightPkg = ResolveWaitInPlacePackage()
    If tightPkg
        ActorUtil.RemovePackageOverride(akActor, tightPkg)
    EndIf
EndFunction

Event OnSkyrimNetPackageRemoved(Form akSender, Form akPackage)
    {SkyrimNet removed a package from an actor. Re-verify with HasPackage
     rather than comparing the passed form, which would mean resolving
     SkyrimNet's FollowPlayer package by EditorID.}
    Actor akActor = akSender as Actor
    If !akActor
        Return
    EndIf
    VerifyCasualFollowPackage(akActor)
EndEvent

Bool Function VerifyCasualFollowPackage(Actor akActor)
    {Clear a legacy casual's hasFollowPkg and follow LinkedRef when SkyrimNet no
     longer holds its FollowPlayer package. Returns true if the flag was stale and
     cleared. Never touches registered followers (the roster owns their follow;
     track-only ones have no SkyrimNet package) or pool-seated casuals.}
    If !akActor
        Return false
    EndIf
    If SeverActionsNativeExt.Native_GetIsFollower(akActor)
        Return false
    EndIf
    If !SeverActionsNative.Native_GetHasFollowPkg(akActor)
        Return false
    EndIf
    ; Pool-seated casual: the alias package needs no SkyrimNet registration.
    If IsInFollowerSlot(akActor)
        Return false
    EndIf
    If SkyrimNetApi.HasPackage(akActor, "FollowPlayer") > 0
        Return false
    EndIf
    SeverActionsNative.Native_SetPackageState(akActor, false, false, false)
    If SeverActions_FollowerFollowKW
        SeverActionsNative.LinkedRef_Clear(akActor, SeverActions_FollowerFollowKW)
    EndIf
    Debug.Trace("[SeverActions_Follow] Cleared stale follow flag on " + akActor.GetDisplayName()         + " - SkyrimNet has no FollowPlayer package; they will no longer be pulled through load doors")
    Return true
EndFunction

Int Function VerifyCasualFollowPackages()
    {Load sweep over casual followers: clear stale follow flags (heals what
     the OnPackageRemoved listener never saw), re-register pool-seated ones
     with OrphanCleanup, migrate legacy SkyrimNet casuals onto the pool and
     erase waiting-faction residue. Returns how many flags were cleared.}
    Actor[] casuals = SeverActionsNativeExt.Native_GetCasualFollowers()
    If !casuals || casuals.Length == 0
        Return 0
    EndIf
    Int cleared = 0
    Int i = 0
    Int residue = 0
    While i < casuals.Length
        If VerifyCasualFollowPackage(casuals[i])
            cleared += 1
        ElseIf casuals[i] && !SeverActionsNativeExt.Native_GetIsFollower(casuals[i])
            If IsInFollowerSlot(casuals[i])
                ; OrphanCleanup's registry is cleared at kPostLoadGame: re-register,
                ; or with the scanner on (orphanCleanupEnabled) the follow LinkedRef
                ; is stripped ~5s in.
                SeverActionsNative.OrphanCleanup_RegisterFollower(casuals[i])
            ElseIf SkyrimNetApi.HasPackage(casuals[i], "FollowPlayer") > 0
                ; Legacy casual on the SkyrimNet override (drops at load doors):
                ; migrate onto the pool, one mechanism only.
                If SeverActions_FollowerFollowKW
                    SeverActionsNative.LinkedRef_Set(casuals[i], Game.GetPlayer(), SeverActions_FollowerFollowKW)
                EndIf
                AssignFollowerSlot(casuals[i])
                SeverActionsNative.OrphanCleanup_RegisterFollower(casuals[i])
                SkyrimNetApi.UnregisterPackage(casuals[i], "FollowPlayer")
                casuals[i].EvaluatePackage()
                Debug.Trace("[SeverActions_Follow] Migrated casual follower " + casuals[i].GetDisplayName() + " onto the follow pool")
            EndIf
        EndIf
        ; Rank -1 is RemoveFromFaction residue that rank-blind checks read as
        ; WAITING (a real wait is rank 0). A non-member also reads -1, but
        ; Faction_RemoveClean is a no-op then.
        If SeverActions_WaitingFaction && casuals[i] && casuals[i].GetFactionRank(SeverActions_WaitingFaction) == -1
            SeverActionsNativeExt2.Faction_RemoveClean(casuals[i], SeverActions_WaitingFaction)
            residue += 1
        EndIf
        i += 1
    EndWhile
    If residue > 0
        Debug.Trace("[SeverActions_Follow] VerifyCasualFollowPackages: erased " + residue + " stale waiting-faction residue(s)")
    EndIf
    If cleared > 0
        Debug.Trace("[SeverActions_Follow] VerifyCasualFollowPackages: cleared " + cleared             + " stale follow flag(s) of " + casuals.Length + " casual follower(s)")
    EndIf
    Return cleared
EndFunction

; Load recovery (SeverActions_Mod_Followers stage 1, before FollowerManager.Maintenance):
; re-registers events and restores state.
Function Maintenance()
    RegisterForModEvent("SeverActionsNative_SandboxCleanup", "OnNativeSandboxCleanup")
    RegisterForModEvent("SeverActions_ExternalWaitAdopt", "OnExternalWaitAdopt")
    RegisterForModEvent("SeverActions_SafeInteriorChanged", "OnSafeInteriorChanged")
    RegisterForModEvent("SeverActions_SafeInteriorToggle", "OnSafeInteriorToggle")
    RegisterForModEvent("SeverActions_PauseOnOpenToggle",  "OnPauseOnOpenToggle")
    RegisterForModEvent("SeverActions_TravelPopupToggle",  "OnTravelPopupToggle")
    RegisterForModEvent("SeverActions_TravelPopupFollowersOnly", "OnTravelPopupFollowersOnly")
    RegisterForModEvent("SeverActions_LLMTrespassToggle",  "OnLLMTrespassToggle")
    RegisterForModEvent("SeverActions_FriendlyFireToggle", "OnFriendlyFireToggle")
    RegisterForModEvent("SeverActions_YieldPromptToggle",  "OnYieldPromptToggle")
    ; Safe-interior heals (see each handler).
    RegisterForModEvent("SeverActions_SafeInteriorReEval", "OnSafeInteriorReEval")
    RegisterForModEvent("SeverActions_SafeInteriorReassert", "OnSafeInteriorReassert")
    RegisterForModEvent("SeverActions_SafeInteriorRelease", "OnSafeInteriorRelease")
    ; A package removed by any route but ours would leave a legacy casual's
    ; hasFollowPkg set, and cell catch-up would keep dragging them around.
    RegisterForModEvent("SkyrimNet_OnPackageRemoved", "OnSkyrimNetPackageRemoved")
    ; The camp muster and the persistence pools register in
    ; SeverActions_Enterprises.Maintenance (P9-03).
    RegisterForModEvent("SeverActions_CasualFollowRecycle", "OnCasualFollowRecycle")

    ; Heal flags that are already stale; the listener above only stops new drift.
    VerifyCasualFollowPackages()

    ; The seven global toggles. The global settings file wins when it holds the
    ; key: this restore and the native replay run in no fixed order, so
    ; ResolveGlobalToggle takes the file's value (mirrored into StorageUtil,
    ; which the 0160 prompt and FollowerManager read). The per-save copy answers
    ; only for keys the file never recorded.
    Quest SeverActionsQuest = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as Quest
    If SeverActionsQuest
        ; Default OFF: the feature races door-transition timing (FF fallback
        ; packages, sticky exits). Opt-in via PrismaUI.
        Bool savedEnabled = ResolveGlobalToggle(SeverActionsQuest, "SeverActions_SafeInteriorEnabled", "safeInteriorSandbox", 0)
        SeverActionsNativeExt.SituationMonitor_SetSafeInteriorEnabled(savedEnabled)
        Debug.Trace("[SeverActions_Follow] Restored safe interior sandbox: " + savedEnabled)

        ; Menu pause-on-open. Default 1 (paused).
        Bool savedPauseOnOpen = ResolveGlobalToggle(SeverActionsQuest, "SeverActions_PauseOnOpen", "pauseOnOpen", 1)
        SeverActionsNative.Magelight_SetPauseOnOpen(savedPauseOnOpen)
        Debug.Trace("[SeverActions_Follow] Restored menu pause on open: " + savedPauseOnOpen)

        ; Travel-destination popup. Default 1 (shown).
        Bool savedTravelPopup = ResolveGlobalToggle(SeverActionsQuest, "SeverActions_TravelPopupEnabled", "travelPopupEnabled", 1)
        SeverActionsNative.Magelight_SetTravelPopupEnabled(savedTravelPopup)
        Debug.Trace("[SeverActions_Follow] Restored travel popup enabled: " + savedTravelPopup)

        ; Popup scope. Default 0 (every traveler).
        Bool savedPopupScope = ResolveGlobalToggle(SeverActionsQuest, "SeverActions_TravelPopupFollowersOnly", "travelPopupFollowersOnly", 0)
        SeverActionsNative.Magelight_SetTravelPopupFollowersOnly(savedPopupScope)
        Debug.Trace("[SeverActions_Follow] Restored travel popup followers-only: " + savedPopupScope)

        ; LLM-driven trespass. Default 1: suppress the vanilla warn-follow loop
        ; and let the confrontation play out in dialogue.
        Bool savedLLMTrespass = ResolveGlobalToggle(SeverActionsQuest, "SeverActions_LLMTrespassEnabled", "llmTrespassEnabled", 1)
        SeverActionsNativeExt.Native_Trespass_SetLLMMode(savedLLMTrespass)
        Debug.Trace("[SeverActions_Follow] Restored LLM trespass mode: " + savedLLMTrespass)

        ; Yield/surrender prompt exposure. Default 1. Held on None: the 0160
        ; combat prompt reads it via papyrus_util GetIntValue with actor 0.
        Bool savedYieldPrompt = ResolveGlobalToggle(None, "SeverActions_YieldPromptEnabled", "yieldPromptEnabled", 1)
        SeverActionsNative.Magelight_SetYieldPromptEnabled(savedYieldPrompt)
        Debug.Trace("[SeverActions_Follow] Restored yield prompt exposure: " + savedYieldPrompt)

        ; Follower friendly-fire prevention. Default 1. The monitor also sets the
        ; ally-hit game settings, which do not ride the save.
        Bool savedFriendlyFire = ResolveGlobalToggle(SeverActionsQuest, "SeverActions_PreventFollowerFF", "preventFollowerFF", 1)
        SeverActionsNative.FriendlyFireMonitor_SetEnabled(savedFriendlyFire)
        Debug.Trace("[SeverActions_Follow] Restored follower friendly-fire prevention: " + savedFriendlyFire)
    EndIf

    ; The safe-interior override and its InSafeInteriorSandbox flag persist in
    ; the save but SituationMonitor's inSafeInterior state does not, so no exit
    ; would ever fire for a follower sandboxing at save time (or when the feature
    ; was turned off). Force the exit; ExitSafeInteriorSandbox no-ops unflagged.
    Actor[] reconFollowers = SeverActionsNative.Native_GetAllTrackedFollowers()
    Int reconIdx = 0
    While reconIdx < reconFollowers.Length
        ExitSafeInteriorSandbox(reconFollowers[reconIdx])
        reconIdx += 1
    EndWhile
EndFunction

Bool Function ResolveGlobalToggle(Form akHolder, String asStorageKey, String asSettingsKey, Int aiDefault)
    {The value a load-time restore applies for one global toggle: the global
     settings file's (true or 1, as the settings handler parses it), mirrored
     into the per-save StorageUtil copy; else (no record, or a DLL without
     the native) the per-save copy.}
    String globalValue = SeverActionsNativeExt2.Native_SettingsGetValue(asSettingsKey, "")
    If globalValue != ""
        Bool enabled = globalValue == "true" || globalValue == "1"
        StorageUtil.SetIntValue(akHolder, asStorageKey, enabled as Int)
        Return enabled
    EndIf
    Return StorageUtil.GetIntValue(akHolder, asStorageKey, aiDefault) == 1
EndFunction

; =============================================================================
; SANDBOX STATE HELPERS
; Native FollowerDataStore.isSandboxing is the source of truth. Never
; SkyrimNetApi.HasPackage("Sandbox"): "Sandbox" isn't in SkyrimNet's
; PackageFormCache, so it always answers false.
; =============================================================================

Bool Function IsSandboxing(Actor akActor)
    {True while SA holds akActor in a manual-wait or safe-interior sandbox.}
    return akActor && SeverActionsNativeExt.Native_GetSandboxing(akActor)
EndFunction

Function SetSandboxFlag(Actor akActor, Bool active)
    If akActor
        SeverActionsNative.Native_SetSandboxing(akActor, active)
    EndIf
EndFunction

; =============================================================================
; NATIVE SANDBOX CLEANUP EVENT HANDLER
; Called by native SandboxManager when player changes cells or moves too far
; =============================================================================

Event OnNativeSandboxCleanup(string eventName, string strArg, float numArg, Form sender)
    Actor akActor = sender as Actor
    if !akActor
        akActor = Game.GetFormEx(numArg as int) as Actor
    endif

    if !akActor
        return
    endif

    ; Only handle actors that are sandboxing through our system
    if !IsSandboxing(akActor)
        return
    endif

    Debug.Trace("[SeverActions_Follow] Native sandbox cleanup for: " + akActor.GetDisplayName())

    ; Clear waiting FIRST so the follow package is eligible before the sandbox
    ; override goes, avoiding an FF-prefix runtime sandbox.
    akActor.SetAV("WaitingForPlayer", 0)
    If SeverActions_WaitingFaction
        ClearWaitingFaction(akActor)
    EndIf

    SetSandboxFlag(akActor, false)

    RemoveWaitSandboxPackages(akActor)

    ; No forced eval: AI resumes follow by itself. Tag only when a follow exists:
    ; a stale tag on a dismissed/homed NPC freezes their work schedule (the
    ; schedule guards read this faction).
    If IsInFollowerSlot(akActor) || SkyrimNetApi.HasPackage(akActor, "FollowPlayer")
        SetActivelyFollowing(akActor, true)
    EndIf

    ; Refill the schedule alias of a dismissed/homed NPC (no-op when follow
    ; just resumed above).
    SeverActions_FollowerManager fmCleanup = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
    If fmCleanup
        fmCleanup.RefillSchedAliasesAfterStop(akActor)
    EndIf

    Debug.Notification(SeverActionsNativeExt2.Native_L10nFmt("follow.stoppedRelaxing", ("" + akActor.GetDisplayName())))
    RegisterFollowStateEvent(akActor, "follower_relax_stopped", akActor.GetDisplayName() + " stops relaxing and catches up with " + Game.GetPlayer().GetDisplayName() + ".")
EndEvent

; =============================================================================
; SAFE INTERIOR AUTO-SANDBOX
; Fired by native SituationMonitor when a following companion enters/exits
; a safe interior (inn, home, shop, temple, town interior).
; =============================================================================

Event OnSafeInteriorChanged(String eventName, String strArg, Float numArg, Form sender)
    ; strArg format: "enter|0xFormID" or "exit|0xFormID"
    Int pipePos = StringUtil.Find(strArg, "|")
    If pipePos < 0
        Return
    EndIf

    String changeType = StringUtil.Substring(strArg, 0, pipePos)
    ; The actor comes from sender: Game.GetForm fails past 0x7FFFFFFF (signed
    ; Int), so the hex strArg is only a Game.GetFormEx fallback.
    Actor akActor = sender as Actor
    If !akActor
        String formIdStr = StringUtil.Substring(strArg, pipePos + 1)
        akActor = Game.GetFormEx(SeverActionsNative.HexToInt(formIdStr)) as Actor
    EndIf
    If !akActor
        Return
    EndIf

    ; A manual wait wins, and a journey refuses a new relax (its exit still runs, to take
    ; a relax under way off a traveler). The monitor has just claimed them on an enter:
    ; yield the claim, or its exit and rescues would move them. Never over our own live
    ; relax (flagged), whose claim it is.
    If akActor.GetAV("WaitingForPlayer") > 0 || (changeType == "enter" && SeverActionsNativeExt2.Travel_GetPhaseByActor(akActor) > 0)
        If changeType == "enter" && StorageUtil.GetIntValue(akActor, "SeverActions_InSafeInteriorSandbox", 0) != 1
            SeverActionsNativeExt2.SituationMonitor_YieldSafeInterior(akActor)
        EndIf
        Return
    EndIf
    ; Leave a dismissed NPC's home sandbox alone; followers with a home still
    ; get the safe-interior sandbox.
    If SeverActionsNative.Native_GetHomeMarkerSlot(akActor) >= 0
        SeverActions_FollowerManager fm = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
        If fm && !fm.IsRegisteredFollower(akActor)
            Return
        EndIf
    EndIf

    If changeType == "enter"
        ; Track-only followers may sandbox too: the enter only lays a temporary
        ; override the exit removes. Re-driving them on the way out would fight
        ; their framework; ExitSafeInteriorSandbox branches on that.
        Package interiorPkg = GetSafeInteriorPackage()
        If interiorPkg && !IsSandboxing(akActor)
            ; Override FIRST, so a valid high-priority package is always there
            ; (SkyrimNet's FollowPlayer hook ignores PO3 priority and races a door
            ; transition into the FE/FF fallback). 4th arg 0 = no AI reset: the
            ; EvaluatePackage below picks it up without the churn flag 1 causes.
            ActorUtil.AddPackageOverride(akActor, interiorPkg, SafeInteriorSandboxPriority, 0)

            ; Drop a legacy SkyrimNet casual's registration (no-op for everyone else).
            SkyrimNetApi.UnregisterPackage(akActor, "FollowPlayer")

            ; WaitingForPlayer = 1 makes SA's alias follow ineligible (it gates on
            ; WFP == 0). Skip it for hands-off followers (track-only, or anyone in
            ; Tracking mode, D45): their framework's follow gates on WFP too, so if
            ; our override lost to a framework re-asserting its package they would
            ; drop to a pinning FF/FE fallback instead of framework follow. The
            ; relax comes from the override, not from WFP.
            If !SeverActions_ModuleBase.IsFollowHandsOff(akActor)
                akActor.SetAV("WaitingForPlayer", 1)
                StorageUtil.UnsetIntValue(akActor, "SeverActions_SafeInteriorNoWfp")
            Else
                ; A WaitingForPlayer above 0 at the exit is then their framework's wait
                ; (ExitSafeInteriorSandbox).
                StorageUtil.SetIntValue(akActor, "SeverActions_SafeInteriorNoWfp", 1)
            EndIf

            SetSandboxFlag(akActor, true)
            StorageUtil.SetIntValue(akActor, "SeverActions_InSafeInteriorSandbox", 1)
            SeverActionsNative.Native_SetSandboxing(akActor, true)
            SetActivelyFollowing(akActor, false)

            ; Same external signal as a manual wait.
            If SeverActions_WaitingFaction
                akActor.AddToFaction(SeverActions_WaitingFaction)
            EndIf

            akActor.EvaluatePackage()
            Debug.Trace("[SeverActions_Follow] Safe interior sandbox: " + akActor.GetDisplayName() + " is relaxing")
        ElseIf IsSandboxing(akActor) && StorageUtil.GetIntValue(akActor, "SeverActions_InSafeInteriorSandbox", 0) != 1
            ; A manual wait whose WaitingForPlayer another script zeroed: the same yield.
            SeverActionsNativeExt2.SituationMonitor_YieldSafeInterior(akActor)
        EndIf
    ElseIf changeType == "exit"
        ExitSafeInteriorSandbox(akActor)
    EndIf
EndEvent

Function ExitSafeInteriorSandbox(Actor akActor)
    {Tear down an active safe-interior auto-sandbox: remove the overrides,
    restore follow, teleport to the player and re-evaluate. No-op unless
    flagged SeverActions_InSafeInteriorSandbox, so safe to call speculatively.
    A relax that wrote no WaitingForPlayer and finds one above 0 was taken over
    by their framework's own wait: only the relax is removed, and they stay.
    A companion Walk With Me leads is released where they stand, not re-driven or moved.}
    If akActor
        If StorageUtil.GetIntValue(akActor, "SeverActions_InSafeInteriorSandbox", 0) == 1
            Bool ownWait = StorageUtil.GetIntValue(akActor, "SeverActions_SafeInteriorNoWfp", 0) == 1 && akActor.GetAV("WaitingForPlayer") > 0
            StorageUtil.UnsetIntValue(akActor, "SeverActions_InSafeInteriorSandbox")
            StorageUtil.UnsetIntValue(akActor, "SeverActions_SafeInteriorNoWfp")
            SetSandboxFlag(akActor, false)
            SeverActionsNative.Native_SetSandboxing(akActor, false)

            ; A traveler: the journey owns them. Only the relax's own package comes off (the wait
            ; packages include the shared 0BDDFF, a waiting traveler's arrival sandbox): no follow
            ; re-driven and no move to the player; the trip's end restores the follower.
            If SeverActionsNativeExt2.Travel_GetPhaseByActor(akActor) > 0
                Package relaxPkg = GetSafeInteriorPackage()
                Bool sharedWithArrival = relaxPkg == SandboxPackage && SeverActionsNativeExt2.Travel_GetPhaseByActor(akActor) == 2
                Int travelIter = 0
                While travelIter < 5 && relaxPkg && !sharedWithArrival
                    ActorUtil.RemovePackageOverride(akActor, relaxPkg)
                    travelIter += 1
                EndWhile
                If !ownWait
                    akActor.SetAV("WaitingForPlayer", 0)
                EndIf
                If SeverActions_WaitingFaction
                    ClearWaitingFaction(akActor)
                EndIf
                akActor.EvaluatePackage()
                Debug.Trace("[SeverActions_Follow] Safe interior sandbox ended: " + akActor.GetDisplayName() + " is traveling, left to the journey")
                Return
            EndIf

            ; Remove repeatedly: one RemovePackageOverride has left the override
            ; on (a flapping enter can stack it) and resetai walked them back
            ; inside. Extra calls are no-ops.
            Int removeIter = 0
            While removeIter < 5
                If SafeInteriorSandboxPackage
                    ActorUtil.RemovePackageOverride(akActor, SafeInteriorSandboxPackage)
                EndIf
                RemoveWaitSandboxPackages(akActor)
                removeIter += 1
            EndWhile

            If ownWait
                If SeverActions_WaitingFaction
                    ClearWaitingFaction(akActor)
                EndIf
                akActor.EvaluatePackage()
                Debug.Trace("[SeverActions_Follow] Safe interior sandbox ended: " + akActor.GetDisplayName() + " left to their own wait")
                Return
            EndIf

            ; Clear WaitingForPlayer before re-driving follow, so the alias
            ; follow is eligible and no engine fallback fills the gap.
            akActor.SetAV("WaitingForPlayer", 0)

            If SeverActions_WaitingFaction
                ClearWaitingFaction(akActor)
            EndIf

            ; Walk With Me leads them: its packages take over where they stand, so no follow
            ; re-driven, no move and no AI reset.
            If SeverActionsNativeExt2.WalkWithMe_Leads(akActor)
                If !SeverActions_ModuleBase.IsFollowHandsOff(akActor)
                    SetActivelyFollowing(akActor, true)
                EndIf
                akActor.EvaluatePackage()
                Debug.Trace("[SeverActions_Follow] Safe interior sandbox ended: " + akActor.GetDisplayName() + " is led by Walk With Me")
                Return
            EndIf

            ; Hands-off followers are never re-driven by SA: release only (done
            ; above), bring them out and re-evaluate so their own follow resumes.
            If SeverActions_ModuleBase.IsFollowHandsOff(akActor)
                akActor.MoveTo(Game.GetPlayer())
                akActor.EvaluatePackage()
                Debug.Trace("[SeverActions_Follow] Safe interior sandbox ended (hands-off release): " + akActor.GetDisplayName() + " — override removed, their own follow resumes")
            Else
                ; Not seated: a legacy SkyrimNet casual, re-register FollowPlayer.
                If !IsInFollowerSlot(akActor)
                    SkyrimNetApi.RegisterPackage(akActor, "FollowPlayer", FollowPackagePriority, 0, true)
                Else
                    ; Re-set SA's follow LinkedRef and OrphanCleanup entry, as
                    ; CompanionStartFollowing does.
                    If SeverActions_FollowerFollowKW
                        SeverActionsNative.LinkedRef_Set(akActor, Game.GetPlayer(), SeverActions_FollowerFollowKW)
                    EndIf
                    SeverActionsNative.OrphanCleanup_RegisterFollower(akActor)
                EndIf

                SetActivelyFollowing(akActor, true)
                ; Teleport to player so they don't get stuck inside the house
                akActor.MoveTo(Game.GetPlayer())

                ; Immediate + 500ms re-eval + resetAI at 1000ms (1500 elsewhere;
                ; they are local). resetAI is harmless here: beside the player,
                ; not in combat.
                SeverActionsNative.EscalatedReEvaluate(akActor, 1000)

                Debug.Trace("[SeverActions_Follow] Safe interior sandbox ended: " + akActor.GetDisplayName() + " teleported to player and resumes following")
            EndIf
        EndIf
    EndIf
EndFunction

Function StripSafeInteriorForFollow(Actor akActor)
    {Light safe-interior teardown for follow-start paths (via
     FollowerManager.StripSandboxesForFollow): drops the overrides and, when
     flagged, the flag and waiting state. Unlike ExitSafeInteriorSandbox it
     neither teleports nor re-drives follow; the caller does that.}
    If !akActor
        Return
    EndIf
    Bool wasFlagged = StorageUtil.GetIntValue(akActor, "SeverActions_InSafeInteriorSandbox", 0) == 1

    ; Remove the override UNCONDITIONALLY: if the flag desyncs from it, a
    ; flag-gated strip leaves a priority-100 override outranking follow (95) and
    ; no entry point can pull them out. Repeated as in ExitSafeInteriorSandbox.
    ; Home / work / furniture sandboxes use other packages and are untouched.
    Int removeIter = 0
    While removeIter < 5
        If SafeInteriorSandboxPackage
            ActorUtil.RemovePackageOverride(akActor, SafeInteriorSandboxPackage)
        EndIf
        RemoveWaitSandboxPackages(akActor)
        removeIter += 1
    EndWhile

    ; State cleanup only when we were actually flagged relaxing.
    If wasFlagged
        StorageUtil.UnsetIntValue(akActor, "SeverActions_InSafeInteriorSandbox")
        StorageUtil.UnsetIntValue(akActor, "SeverActions_SafeInteriorNoWfp")
        SetSandboxFlag(akActor, false)
        SeverActionsNative.Native_SetSandboxing(akActor, false)
        akActor.SetAV("WaitingForPlayer", 0)
        If SeverActions_WaitingFaction
            ClearWaitingFaction(akActor)
        EndIf
        Debug.Trace("[SeverActions_Follow] Safe interior sandbox stripped for follow start: " + akActor.GetDisplayName())
    EndIf

    ; Re-evaluate even unflagged (the desync case), or the stale override stays
    ; selected until the next tick. Runs per follow command, never per tick.
    akActor.EvaluatePackage()
EndFunction

Bool Function YieldSafeInteriorToWait(Actor akActor, Package akWaitPackage)
    {A wait takes over from the safe-interior relax: drop the relax override (unless it
     is akWaitPackage, the package the wait itself holds; None when SA holds none) and
     its flag, and yield SituationMonitor's claim, so neither the claim's exit nor a
     rescue moves the waiter. Writes no WaitingForPlayer, sandbox flag or faction.
     True when the relax flag was set.}
    If !akActor
        Return False
    EndIf
    Bool wasFlagged = StorageUtil.GetIntValue(akActor, "SeverActions_InSafeInteriorSandbox", 0) == 1
    ; The relax can ride SandboxPackage (GetSafeInteriorPackage's fallback), the wide
    ; wait's own package, which must stay when the wait holds it. Repeated as in
    ; ExitSafeInteriorSandbox.
    Package relaxPkg = GetSafeInteriorPackage()
    If relaxPkg && relaxPkg != akWaitPackage
        Int removeIter = 0
        While removeIter < 5
            ActorUtil.RemovePackageOverride(akActor, relaxPkg)
            removeIter += 1
        EndWhile
    EndIf
    If wasFlagged
        StorageUtil.UnsetIntValue(akActor, "SeverActions_InSafeInteriorSandbox")
        StorageUtil.UnsetIntValue(akActor, "SeverActions_SafeInteriorNoWfp")
    EndIf
    SeverActionsNativeExt2.SituationMonitor_YieldSafeInterior(akActor)
    Return wasFlagged
EndFunction

; SituationMonitor fires this ~500ms after the enter, in case the first
; EvaluatePackage raced a cell transition.
Event OnSafeInteriorReEval(String eventName, String strArg, Float numArg, Form sender)
    ; sender always carries the actor (the three safe-interior heals share this);
    ; numArg is 0 - a float FormID corrupts above 2^24.
    Actor akActor = sender as Actor
    If !akActor
        Return
    EndIf
    ; Still flagged? The player may have left during the delay (mid-exit).
    If StorageUtil.GetIntValue(akActor, "SeverActions_InSafeInteriorSandbox", 0) != 1
        Return
    EndIf
    akActor.EvaluatePackage()
    Debug.Trace("[SeverActions_Follow] Safe interior deferred re-eval: " + akActor.GetDisplayName())
EndEvent

Event OnSafeInteriorReassert(String eventName, String strArg, Float numArg, Form sender)
    {A follower flagged safe-interior sandboxing was found on a runtime FF/FE
     fallback (the override lost selection, or a transition or load knocked it
     off). Re-ADD the override: a bare EvaluatePackage does not recover them.}
    Actor akActor = sender as Actor
    If !akActor || akActor.IsDead()
        Return
    EndIf
    ; Same gate as OnSafeInteriorReEval.
    If StorageUtil.GetIntValue(akActor, "SeverActions_InSafeInteriorSandbox", 0) != 1
        Return
    EndIf
    Package interiorPkg = GetSafeInteriorPackage()
    If interiorPkg
        ; WaitingForPlayer / faction / flags from the enter are still right.
        ; 4th arg 0 = no AI reset, as on enter.
        ActorUtil.AddPackageOverride(akActor, interiorPkg, SafeInteriorSandboxPriority, 0)
        akActor.EvaluatePackage()
        Debug.Trace("[SeverActions_Follow] Safe interior sandbox RE-ASSERTED off FF fallback: " + akActor.GetDisplayName())
    EndIf
EndEvent

Event OnSafeInteriorRelease(String eventName, String strArg, Float numArg, Form sender)
    {The mirror of OnSafeInteriorReassert: SandboxHealTick found this TRACK-ONLY
     follower driven by her own framework's follow, so let go. Native already
     cleared our native flags; strip the lingering override without
     teleporting or re-driving her.}
    Actor akActor = sender as Actor
    If !akActor
        Return
    EndIf
    StripSafeInteriorForFollow(akActor)
EndEvent

; =============================================================================
; SETTINGS TOGGLE EVENTS
; Sent by the settings handler after it fed the toggle's Authority row, which
; is what persists it (no StorageUtil copy is written here, check 22c). The
; handlers only re-sync live state.
; =============================================================================

Event OnSafeInteriorToggle(String eventName, String strArg, Float numArg, Form sender)
    Quest SeverActionsQuest = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as Quest
    If SeverActionsQuest
        Int val = 0
        If numArg >= 1.0
            val = 1
        EndIf
        Debug.Trace("[SeverActions_Follow] Safe interior sandbox toggle persisted: " + val)
    EndIf
EndEvent

Event OnPauseOnOpenToggle(String eventName, String strArg, Float numArg, Form sender)
    {Log only: the settings handler already set the native flag, and
     Maintenance re-pushes it on load.}
    Quest SeverActionsQuest = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as Quest
    If SeverActionsQuest
        Int val = 0
        If numArg >= 1.0
            val = 1
        EndIf
        Debug.Trace("[SeverActions_Follow] Menu pause-on-open toggle persisted: " + val)
    EndIf
EndEvent

Event OnTravelPopupFollowersOnly(String eventName, String strArg, Float numArg, Form sender)
    {Re-syncs the followers-only popup scope (already set C++-side).}
    Quest SeverActionsQuest = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as Quest
    If SeverActionsQuest
        Int val = 0
        If numArg >= 1.0
            val = 1
        EndIf
        SeverActionsNative.Magelight_SetTravelPopupFollowersOnly(val == 1)
        Debug.Trace("[SeverActions_Follow] Travel popup followers-only persisted: " + val)
    EndIf
EndEvent

Event OnTravelPopupToggle(String eventName, String strArg, Float numArg, Form sender)
    {Re-syncs the travel-destination popup toggle (already set C++-side).}
    Quest SeverActionsQuest = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as Quest
    If SeverActionsQuest
        Int val = 0
        If numArg >= 1.0
            val = 1
        EndIf
        SeverActionsNative.Magelight_SetTravelPopupEnabled(val == 1)
        Debug.Trace("[SeverActions_Follow] Travel popup toggle persisted: " + val)
    EndIf
EndEvent

Event OnLLMTrespassToggle(String eventName, String strArg, Float numArg, Form sender)
    {Re-syncs the native LLM-trespass flag the vfunc hook reads.}
    Quest SeverActionsQuest = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as Quest
    If SeverActionsQuest
        Int val = 0
        If numArg >= 1.0
            val = 1
        EndIf
        SeverActionsNativeExt.Native_Trespass_SetLLMMode(val == 1)
        Debug.Trace("[SeverActions_Follow] LLM trespass toggle persisted: " + val)
    EndIf
EndEvent

Event OnYieldPromptToggle(String eventName, String strArg, Float numArg, Form sender)
    {"Yield / Surrender Context" (Settings > Prompt Filters): re-syncs the
     native flag the settings gather reads. The 0160 prompt's StorageUtil(None)
     mirror SeverActions_YieldPromptEnabled follows every feed (M-X).}
    Int val = 0
    If numArg >= 1.0
        val = 1
    EndIf
    SeverActionsNative.Magelight_SetYieldPromptEnabled(val == 1)
    Debug.Trace("[SeverActions_Follow] Yield prompt exposure toggle persisted: " + val)
EndEvent

Event OnFriendlyFireToggle(String eventName, String strArg, Float numArg, Form sender)
    {"Prevent Follower Friendly Fire" changed. The settings handler already set the native
     monitor, which owns the ally-hit game settings too.}
    Debug.Trace("[SeverActions_Follow] Follower friendly-fire prevention: " + (numArg >= 1.0))
EndEvent

; =============================================================================
; HELPER - Check if actor has follow package
; =============================================================================

Bool Function HasFollowPackage(Actor akActor)
    {True while akActor actively follows: IsInFollowerSlot (pool seat, legacy
     slot or overflow) or a legacy SkyrimNet FollowPlayer registration.
     Mechanism-based on purpose: do NOT test the
     ActivelyFollowing faction, whose membership has survived removal and
     wedged the hotkey/wheel follow toggle. It is a prompt tag, not state.}
    if !akActor
        return false
    endif
    If IsInFollowerSlot(akActor)
        return true
    EndIf
    return SkyrimNetApi.HasPackage(akActor, "FollowPlayer")
EndFunction

; =============================================================================
; ACTIVELY FOLLOWING FACTION — dynamic state for SkyrimNet prompt integration
; =============================================================================

Function SetActivelyFollowing(Actor akActor, Bool active)
    {Add or remove the SeverActions_ActivelyFollowing faction on every follow
     state change.}
    If !SeverActions_ActivelyFollowing || !akActor
        Return
    EndIf
    If active
        akActor.AddToFaction(SeverActions_ActivelyFollowing)
    Else
        ; TRUE removal (RemoveFromFaction leaves rank -1 residue; see
        ; ClearWaitingFaction). removedClean goes in the warning below.
        Bool removedClean = SeverActionsNativeExt2.Faction_RemoveClean(akActor, SeverActions_ActivelyFollowing)
        ; A membership has survived RemoveClean (issue #437): on a real survivor
        ; (rank >= 0; a non-member reads -1) log loudly and fall back to
        ; RemoveFromFaction. Its -1 residue is acceptable: follow detection reads
        ; the pool seat and SkyrimNet readers test get_faction_rank >= 0.
        Int survivedRank = akActor.GetFactionRank(SeverActions_ActivelyFollowing)
        If survivedRank >= 0
            Debug.Trace("[SeverActions_Follow] WARNING: ActivelyFollowing survived Faction_RemoveClean on " + akActor.GetDisplayName() + " (rank " + survivedRank + ", removedClean=" + removedClean + ") - RemoveFromFaction fallback applied")
            akActor.RemoveFromFaction(SeverActions_ActivelyFollowing)
        EndIf
    EndIf
EndFunction

Function ClearWaitingFaction(Actor akActor)
    {TRUE removal of the waiting faction. RemoveFromFaction only writes rank
     -1, which rank-blind readers (IsInFaction, GetInFaction package
     conditions, IntelEngine's wait check) still read as WAITING - casual
     followers froze at load doors that way.}
    If !akActor || !SeverActions_WaitingFaction
        Return
    EndIf
    SeverActionsNativeExt2.Faction_RemoveClean(akActor, SeverActions_WaitingFaction)
EndFunction

; =============================================================================
; FOLLOW ALIAS POOL
; =============================================================================

Quest Function GetFollowQuest()
    {The 200-alias follow quest, resolved by FormID (never an ESP property)
     and cached once found. None on an ESP without the pool (AssignFollowerSlot
     then uses the legacy slots); retried each call until it resolves.}
    If _followQuestResolved
        Return _followQuest
    EndIf
    _followQuest = Game.GetFormFromFile(FOLLOW_QUEST_FORMID, "SeverActions.esp") as Quest
    If !_followQuest
        Debug.Trace("[SeverActions_Follow] FOLLOW ALIAS POOL UNAVAILABLE — SeverActions_FollowQuest failed to resolve from SeverActions.esp (outdated ESP?). Pool seating disabled; legacy 21-slot + overflow follow remains active.")
        Return None
    EndIf
    _followQuestResolved = true
    Return _followQuest
EndFunction

ReferenceAlias Function GetFollowAlias(Int aiIndex)
    If aiIndex < 0 || aiIndex >= FOLLOW_ALIAS_POOL_SIZE
        Return None
    EndIf
    Quest pool = GetFollowQuest()
    If !pool
        Return None
    EndIf
    Return pool.GetNthAlias(aiIndex) as ReferenceAlias
EndFunction

Function AssignFollowerSlot(Actor akActor)
    {Seat the actor in the follow pool (the alias packages apply on ForceRefTo
     and re-apply on cell load). A legacy slot or overflow pair is stripped
     first so one mechanism drives follow; overflow is only the >200 fallback.}
    If !akActor
        Return
    EndIf
    Quest pool = GetFollowQuest()
    If pool
        ; Already-seated fast path: the cosaved index names an alias that
        ; still points at this actor.
        Int held = SeverActionsNativeExt.Native_GetFollowAliasIndex(akActor)
        If held >= 0
            ReferenceAlias heldAl = GetFollowAlias(held)
            If heldAl && heldAl.GetReference() == akActor
                Return
            EndIf
            ; Stale index (alias repurposed): drop it; SweepFollowAliasesOnLoad
            ; checks the pool side.
            SeverActionsNativeExt.Native_SetFollowAliasIndex(akActor, -1)
        EndIf
        ; A pre-pool save can hold a legacy slot or the overflow pair; two
        ; stacked mechanisms flicker the AI.
        _ClearLegacyFollowerSlot(akActor)
        If StorageUtil.GetIntValue(akActor, "SeverFollow_Overflow", 0) == 1
            RemoveOverflowFollow(akActor)
        EndIf
        ; The pool's claim (plan M-W, P2-09): a free alias, or the one this actor
        ; already fills; the fill itself stays here (F19).
        Int idx = SeverActionsNativeExt2.FollowPool_Claim(akActor, "follow")
        If idx >= 0
            ReferenceAlias al = GetFollowAlias(idx)
            If al
                al.ForceRefTo(akActor)
                SeverActionsNativeExt.Native_SetFollowAliasIndex(akActor, idx)
                If StorageUtil.GetIntValue(akActor, "SeverCamp_MusterAlias", -1) == idx
                    ; A mustered camp member recruited: the claim is now "follow", so
                    ; drop the muster keys (a send-home must not clear this seat).
                    StorageUtil.UnsetIntValue(akActor, "SeverCamp_MusterAlias")
                    StorageUtil.UnsetFloatValue(akActor, "SeverCamp_MusterETA")
                EndIf
                Debug.Trace("[SeverActions_Follow] Seated " + akActor.GetDisplayName() + " in follow alias " + idx)
                Return
            EndIf
            SeverActionsNativeExt2.FollowPool_Release(idx)   ; no alias object behind the index: the claim goes back
        EndIf
        ; Pool full (>200 followers): the override pair.
        ApplyOverflowFollow(akActor)
        Return
    EndIf
    ; ESP without the pool: legacy slots.
    _AssignLegacyFollowerSlot(akActor)
EndFunction

Function _AssignLegacyFollowerSlot(Actor akActor)
    {Pre-pool ESP only: the 21 CK slots, then overflow. Never fill a legacy
     slot otherwise.}
    If !FollowerSlots
        Debug.Trace("[SeverActions_Follow] WARNING: FollowerSlots array not set - alias follow disabled")
        Return
    EndIf

    ; Check if actor is already in a slot (avoid duplicates)
    Int i = 0
    While i < FollowerSlots.Length
        If FollowerSlots[i] && FollowerSlots[i].GetActorRef() == akActor
            Debug.Trace("[SeverActions_Follow] " + akActor.GetDisplayName() + " already in FollowerSlot" + i)
            Return
        EndIf
        i += 1
    EndWhile

    ; Find first empty slot
    i = 0
    While i < FollowerSlots.Length
        If FollowerSlots[i] && !FollowerSlots[i].GetActorRef()
            ; Strip overflow overrides first, or the alias package and the PO3
            ; pair run together (AI flicker).
            If StorageUtil.GetIntValue(akActor, "SeverFollow_Overflow", 0) == 1
                RemoveOverflowFollow(akActor)
            EndIf
            FollowerSlots[i].ForceRefTo(akActor)
            Debug.Trace("[SeverActions_Follow] Assigned " + akActor.GetDisplayName() + " to FollowerSlot" + i)
            Return
        EndIf
        i += 1
    EndWhile

    ; All 21 slots taken: ride the same packages as PO3 overrides (appending
    ; aliases to this quest hangs the engine). Their own conditions still gate
    ; them (Close on CloseFollowFaction, both on WaitingForPlayer == 0), and
    ; FollowDriftMonitor re-asserts drift.
    ApplyOverflowFollow(akActor)
EndFunction

Function _ClearLegacyFollowerSlot(Actor akActor)
    {Clear the actor's legacy CK slot if held (usually a no-op).}
    If !FollowerSlots
        Return
    EndIf
    Int i = 0
    While i < FollowerSlots.Length
        If FollowerSlots[i] && FollowerSlots[i].GetActorRef() == akActor
            FollowerSlots[i].Clear()
            Debug.Trace("[SeverActions_Follow] Cleared " + akActor.GetDisplayName() + " from FollowerSlot" + i)
            Return
        EndIf
        i += 1
    EndWhile
EndFunction

Function ApplyOverflowFollow(Actor akActor)
    {Follow via package override for followers beyond the alias pool. Close
     (faction-gated, prio 55) above V2 (prio 50) — both below the sandbox/
     wait overrides (100+) so Wait/relax still wins.}
    Package closePkg = Game.GetFormFromFile(0x0016567C, "SeverActions.esp") as Package
    Package v2Pkg = Game.GetFormFromFile(0x00155C93, "SeverActions.esp") as Package
    If closePkg
        ActorUtil.AddPackageOverride(akActor, closePkg, 55, 1)
    EndIf
    If v2Pkg
        ActorUtil.AddPackageOverride(akActor, v2Pkg, 50, 1)
    EndIf
    StorageUtil.SetIntValue(akActor, "SeverFollow_Overflow", 1)
    akActor.EvaluatePackage()
    Debug.Trace("[SeverActions_Follow] OVERFLOW follow (no free alias slot) applied to " + akActor.GetDisplayName())
EndFunction

Function RemoveOverflowFollow(Actor akActor)
    {Strip the overflow follow overrides. Safe no-op when never applied.}
    If StorageUtil.GetIntValue(akActor, "SeverFollow_Overflow", 0) != 1
        Return
    EndIf
    Package closePkg = Game.GetFormFromFile(0x0016567C, "SeverActions.esp") as Package
    Package v2Pkg = Game.GetFormFromFile(0x00155C93, "SeverActions.esp") as Package
    If closePkg
        ActorUtil.RemovePackageOverride(akActor, closePkg)
    EndIf
    If v2Pkg
        ActorUtil.RemovePackageOverride(akActor, v2Pkg)
    EndIf
    StorageUtil.UnsetIntValue(akActor, "SeverFollow_Overflow")
    akActor.EvaluatePackage()
    Debug.Trace("[SeverActions_Follow] Overflow follow removed from " + akActor.GetDisplayName())
EndFunction

Function ClearFollowerSlot(Actor akActor)
    {Release the actor's follow alias (which drops its packages), plus any
     legacy slot or overflow pair.}
    If !akActor
        Return
    EndIf
    RemoveOverflowFollow(akActor)
    Int held = SeverActionsNativeExt.Native_GetFollowAliasIndex(akActor)
    If held >= 0
        ReferenceAlias heldAl = GetFollowAlias(held)
        If heldAl && heldAl.GetReference() == akActor
            heldAl.Clear()
            SeverActionsNativeExt2.FollowPool_Release(held)
        ElseIf heldAl && heldAl.GetReference() == None
            SeverActionsNativeExt2.FollowPool_Release(held)   ; the alias is empty: whatever claim sat on it is stale
        EndIf
        ; Drop the index either way; SweepFollowAliasesOnLoad checks the pool side.
        SeverActionsNativeExt.Native_SetFollowAliasIndex(akActor, -1)
        Debug.Trace("[SeverActions_Follow] Freed follow alias " + held + " for " + akActor.GetDisplayName())
    Else
        ; No index (e.g. ClearFollowerData ran first on a dismiss): scan the
        ; pool so the alias can't leak filled and keep them following.
        Int scan = 0
        While scan < FOLLOW_ALIAS_POOL_SIZE
            ReferenceAlias scanAl = GetFollowAlias(scan)
            If scanAl && scanAl.GetReference() == akActor
                scanAl.Clear()
                SeverActionsNativeExt2.FollowPool_Release(scan)
                Debug.Trace("[SeverActions_Follow] Freed follow alias " + scan + " for " + akActor.GetDisplayName() + " (pool scan fallback)")
            EndIf
            scan += 1
        EndWhile
    EndIf
    _ClearLegacyFollowerSlot(akActor)
EndFunction

Bool Function IsInFollowerSlot(Actor akActor)
    {True when the actor's follow is driven by the pool (cosaved index +
     alias content), a legacy CK slot or the overflow pair. Pool-seated
     casuals count too: the roster (Native_GetIsFollower), not this, tells
     companions from casuals.}
    If !akActor
        Return false
    EndIf
    Int held = SeverActionsNativeExt.Native_GetFollowAliasIndex(akActor)
    If held >= 0
        ReferenceAlias heldAl = GetFollowAlias(held)
        If heldAl && heldAl.GetReference() == akActor
            Return true
        EndIf
    EndIf
    If StorageUtil.GetIntValue(akActor, "SeverFollow_Overflow", 0) == 1
        Return true
    EndIf
    If !FollowerSlots
        Return false
    EndIf
    Int i = 0
    While i < FollowerSlots.Length
        If FollowerSlots[i] && FollowerSlots[i].GetActorRef() == akActor
            Return true
        EndIf
        i += 1
    EndWhile
    Return false
EndFunction

; =============================================================================
; FOLLOW POOL — load-time adoption + reconciliation sweep
; =============================================================================

Function SweepFollowAliasesOnLoad(Actor[] followers)
    {Load-time follow-pool reconciliation (FollowerManager.RunDeferredMaintenance,
     before ReapplyFollowTracking so that pass sees pool state).
     Migration (one-shot, sentinel SeverActions_FollowPoolMigDone): adopt
     followers from legacy CK slots or the overflow pair into the pool.
     Verify (every load): empty aliases holding deleted/disabled actors or
     non-followers (a seat Enterprises' war-band record names excepted), resolve duplicates
     to the recorded index, adopt unrecorded fills, release claims on empty
     aliases, drop stale roster indices.}
    Quest pool = GetFollowQuest()
    If !pool
        Return
    EndIf
    SeverActions_FollowerManager fmSwp = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager

    ; ── Migration half (one-shot) ──
    If StorageUtil.GetIntValue(None, "SeverActions_FollowPoolMigDone", 0) == 0
        Int mi = 0
        While mi < followers.Length
            Actor mf = followers[mi]
            If mf && !mf.IsDead()
                ; Same skips as ReapplyFollowTracking: hands-off actors, and
                ; mid-travel companions (seated when the trip ends).
                Bool migSkip = false
                If SeverActions_ModuleBase.IsFollowHandsOff(mf)
                    migSkip = true
                ElseIf SeverActionsNativeExt2.Native_GetTravelState(mf) != ""
                    migSkip = true
                EndIf
                If !migSkip
                    Bool adopted = false
                    If FollowerSlots
                        Int si = 0
                        While si < FollowerSlots.Length
                            If FollowerSlots[si] && FollowerSlots[si].GetActorRef() == mf
                                FollowerSlots[si].Clear()
                                adopted = true
                                Debug.Trace("[SeverActions_Follow] FollowPool migration: " + mf.GetDisplayName() + " adopted from legacy FollowerSlot" + si)
                            EndIf
                            si += 1
                        EndWhile
                    EndIf
                    If StorageUtil.GetIntValue(mf, "SeverFollow_Overflow", 0) == 1
                        RemoveOverflowFollow(mf)
                        adopted = true
                        Debug.Trace("[SeverActions_Follow] FollowPool migration: " + mf.GetDisplayName() + " adopted from overflow overrides")
                    EndIf
                    If adopted
                        AssignFollowerSlot(mf)
                    EndIf
                EndIf
            EndIf
            mi += 1
        EndWhile
        StorageUtil.SetIntValue(None, "SeverActions_FollowPoolMigDone", 1)
        Debug.Trace("[SeverActions_Follow] FollowPool migration pass complete (sentinel set)")
    EndIf

    ; ── Verify half (every load) ──
    ; Pool side: empty orphans; resolve duplicates to the recorded index;
    ; adopt content where the index is missing/stale.
    Int i = 0
    While i < FOLLOW_ALIAS_POOL_SIZE
        ReferenceAlias al = pool.GetNthAlias(i) as ReferenceAlias
        If al
            Actor a = al.GetReference() as Actor
            If a
                If a.IsDeleted() || a.IsDisabled()
                    al.Clear()
                    SeverActionsNativeExt2.FollowPool_Release(i)
                    Debug.Trace("[SeverActions_Follow] FollowPool sweep: emptied alias " + i + " (deleted/disabled holder)")
                ElseIf (!fmSwp || !fmSwp.IsRegisteredFollower(a)) && !SeverActionsNative.Native_GetHasFollowPkg(a)
                    ; Neither a registered companion nor a casual (a pool-seated
                    ; casual has hasFollowPkg and no roster row): the seat and SA's
                    ; follow LinkedRef go, unless Enterprises' war-band record names it.
                    If !_IsWarBandSeat(a, i)
                        al.Clear()
                        SeverActionsNativeExt2.FollowPool_Release(i)
                        If SeverActions_FollowerFollowKW && a.GetLinkedRef(SeverActions_FollowerFollowKW) != None
                            SeverActionsNative.LinkedRef_Clear(a, SeverActions_FollowerFollowKW)
                        EndIf
                        Debug.Trace("[SeverActions_Follow] FollowPool sweep: emptied alias " + i + " (holder neither companion nor casual)")
                    EndIf
                Else
                    Int claimed = SeverActionsNativeExt.Native_GetFollowAliasIndex(a)
                    If claimed != i
                        If claimed >= 0
                            ReferenceAlias other = GetFollowAlias(claimed)
                            If other && other.GetReference() == a
                                al.Clear()   ; duplicate fill — the recorded one wins
                                SeverActionsNativeExt2.FollowPool_Release(i)
                                Debug.Trace("[SeverActions_Follow] FollowPool sweep: emptied duplicate alias " + i + " for " + a.GetDisplayName())
                            Else
                                SeverActionsNativeExt.Native_SetFollowAliasIndex(a, i)   ; recorded index was stale — adopt
                                SeverActionsNativeExt2.FollowPool_Claim(a, "follow")   ; adopts alias i (filled by a)
                            EndIf
                        Else
                            SeverActionsNativeExt.Native_SetFollowAliasIndex(a, i)   ; adopt
                            SeverActionsNativeExt2.FollowPool_Claim(a, "follow")   ; adopts alias i (filled by a)
                        EndIf
                    EndIf
                EndIf
            ElseIf SeverActionsNativeExt2.FollowPool_OwnerOf(i) != ""
                ; An empty alias keeps no claim (its holder deleted, a fill lost to
                ; the stale alias table); the sweep runs before any seating, so no
                ; claim here is mid-seat.
                SeverActionsNativeExt2.FollowPool_Release(i)
            EndIf
        EndIf
        i += 1
    EndWhile
    ; Roster side: drop recorded indices whose alias no longer points at
    ; the follower (the next AssignFollowerSlot re-seats them).
    Int ri = 0
    While ri < followers.Length
        Actor rf = followers[ri]
        If rf
            Int rIdx = SeverActionsNativeExt.Native_GetFollowAliasIndex(rf)
            If rIdx >= 0
                ReferenceAlias ral = GetFollowAlias(rIdx)
                If !ral || ral.GetReference() != rf
                    If ral && ral.GetReference() == None
                        SeverActionsNativeExt2.FollowPool_Release(rIdx)   ; the empty alias keeps no claim
                    EndIf
                    SeverActionsNativeExt.Native_SetFollowAliasIndex(rf, -1)
                    Debug.Trace("[SeverActions_Follow] FollowPool sweep: dropped stale index " + rIdx + " for " + rf.GetDisplayName())
                EndIf
            EndIf
        EndIf
        ri += 1
    EndWhile
    Debug.Trace("[SeverActions_Follow] FollowPool load sweep complete")
EndFunction

Bool Function _IsWarBandSeat(Actor akHolder, Int aiIndex)
    {True when alias aiIndex is a war-band member's seat by SeverActions_Enterprises' own record
     (SeverCamp_MusterAlias: set at muster, cleared by every send-home, unmuster, death relay and
     recruit), so a seat the record no longer names still goes at load. Never for a follower
     another framework owns, a loaded corpse, nor without the enterprises module.}
    If !SeverActionsNativeExt2.Module_IsUsable("enterprises") || SeverActionsNativeExt2.Native_IsTrackOnlyFollower(akHolder)
        Return false
    EndIf
    ; IsDead can misread an unloaded living actor at load; the death relay clears a real corpse's
    ; record anyway.
    If akHolder.IsDead() && akHolder.Is3DLoaded()
        Return false
    EndIf
    ; The record, not a camp lookup: it is what every send-home and unmuster frees the seat by.
    Return StorageUtil.GetIntValue(akHolder, "SeverCamp_MusterAlias", -1) == aiIndex
EndFunction

; =============================================================================
; CAMP MUSTER AND PERSISTENCE POOLS - moved to SeverActions_Enterprises (P9-03,
; plan B21). Below are their safe-exit stubs (F7); OnCasualFollowRecycle among
; them is Follow's own.
; =============================================================================

Function MusterCampById(Int aiCampId)
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
EndFunction

Int Function _MusterOne(Actor m, Actor akPlayer)
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).
     Returns -1 (skipped): an old caller frame counts 0 as fell-in and 1 as set out.}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
    Return -1
EndFunction

Quest Function GetCampPersistQuest()
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
    Return None
EndFunction

ReferenceAlias Function GetCampPersistAlias(Int aiIndex)
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
    Return None
EndFunction

Function _UnpersistOne(Actor akMember)
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
EndFunction

Function SweepCampPersistPool()
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
EndFunction

Quest Function GetRetainerPersistQuest()
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
    Return None
EndFunction

ReferenceAlias Function GetRetainerPersistAlias(Int aiIndex)
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
    Return None
EndFunction

Function _UnpersistOneRetainer(Actor akRetainer)
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
EndFunction

Function SweepRetainerPersistPool()
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
EndFunction

Event OnCasualFollowRecycle(String eventName, String strArg, Float numArg, Form sender)
    {Cell catchup just moved a CASUAL follower to the player. Across a load
     door SkyrimNet's FollowPlayer can stay registered yet stop being served;
     re-cycling the registration relinks its hook. Idempotent, and never
     resurrects a stopped follow (only a registered package is cycled).}
    Actor m = sender as Actor
    If !m || m.IsDead()
        Return
    EndIf
    ; Pool-seated: the alias package re-applies on cell load; just nudge.
    If IsInFollowerSlot(m)
        m.EvaluatePackage()
        Return
    EndIf
    If !SkyrimNetApi.HasPackage(m, "FollowPlayer")
        Return
    EndIf
    SkyrimNetApi.UnregisterPackage(m, "FollowPlayer")
    SkyrimNetApi.RegisterPackage(m, "FollowPlayer", FollowPackagePriority, 0, true)
    m.EvaluatePackage()
    Debug.Trace("[SeverActions_Follow] CasualFollowRecycle: relinked FollowPlayer for " + m.GetDisplayName())
EndEvent

Function SendCampHomeById(Int aiCampId)
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
EndFunction

Int Function _UnmusterOne(Actor akMember, ObjectReference akHome)
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
    Return 0
EndFunction

Int Function _PumpMusterArrivals()
    {Safe-exit stub: the body moved to SeverActions_Enterprises (P9-03, plan B21).}
    ; M-I-STUB 3.9.14-beta25 (P9-03): moved to SeverActions_Enterprises
    Return 0
EndFunction

; =============================================================================
; SAVE/LOAD PERSISTENCE (Companions only)
; =============================================================================

Function ReapplyFollowTracking(Actor[] followers)
    {Load re-apply for the roster (FollowerManager.RunDeferredMaintenance).
     Alias packages persist natively; this re-sets the follow LinkedRef and
     OrphanCleanup entry, the wait sandbox, the ActivelyFollowing tag and the
     native follow flag, and takes the flag and LinkedRef off a hands-off
     follower. Never registers a SkyrimNet package.}
    Actor player = Game.GetPlayer()
    Int i = 0
    While i < followers.Length
        Actor akActor = followers[i]
        Bool skipReapply = false
        If akActor && !akActor.IsDead()
            ; Hands-off (track-only, or anyone in Tracking mode, D45): never set
            ; SA's LinkedRef / OrphanCleanup entry / hasFollowPkg, and clear a stale
            ; flag (it re-arms FollowDriftMonitor, CellCatchup and SandboxManager
            ; against them) or LinkedRef, every load. No EvaluatePackage: their
            ; framework owns their packages.
            If SeverActions_ModuleBase.IsFollowHandsOff(akActor)
                skipReapply = true
                SeverActionsNative.Native_SetPackageState(akActor, false, false, false)
                If SeverActions_FollowerFollowKW && akActor.GetLinkedRef(SeverActions_FollowerFollowKW) != None
                    SeverActionsNative.LinkedRef_Clear(akActor, SeverActions_FollowerFollowKW)
                EndIf
                Debug.Trace("[SeverActions_Follow] ReapplyFollowTracking: skipped hands-off " + akActor.GetDisplayName() + " (owned elsewhere, or Tracking mode - SA leads nobody)")
            ; Mid-travel: Travel's load recovery owns them.
            ElseIf SeverActionsNativeExt2.Native_GetTravelState(akActor) != ""
                skipReapply = true
                Debug.Trace("[SeverActions_Follow] ReapplyFollowTracking: skipped mid-travel " + akActor.GetDisplayName())
            EndIf
        EndIf
        If akActor && !akActor.IsDead() && !skipReapply
            ; A seated follower must not also hold SkyrimNet's FollowPlayer (AI
            ; flicker).
            If IsInFollowerSlot(akActor) && SkyrimNetApi.HasPackage(akActor, "FollowPlayer")
                SkyrimNetApi.UnregisterPackage(akActor, "FollowPlayer")
                Debug.Trace("[SeverActions_Follow] Cleaned stale SkyrimNet FollowPlayer from companion: " + akActor.GetDisplayName())
            EndIf

            ; Re-set every load: the cosave restore does not refresh the row's
            ; 30-day prune stamp.
            If SeverActions_FollowerFollowKW
                SeverActionsNative.LinkedRef_Set(akActor, player, SeverActions_FollowerFollowKW)
                ; OrphanCleanup's registry is cleared at every kPostLoadGame; with
                ; the scanner on (orphanCleanupEnabled) an unregistered holder's
                ; LinkedRef is stripped ~5s after load.
                SeverActionsNative.OrphanCleanup_RegisterFollower(akActor)
            EndIf

            ; Either signal means waiting: external AI (Serana's DLC scripts) can
            ; zero WaitingForPlayer, but only SA clears the native sandboxing flag.
            Bool isWaiting = akActor.GetAV("WaitingForPlayer") > 0 || IsSandboxing(akActor)
            ; 4th arg 0 = no AI reset; the EvaluatePackage below picks it up.
            If isWaiting && SandboxPackage
                ActorUtil.AddPackageOverride(akActor, GetWaitSandboxPackage(), SandboxPackagePriority, 0)
                SetSandboxFlag(akActor, true)
            EndIf

            SetActivelyFollowing(akActor, !isWaiting)

            ; Native follow flag (drift monitor, cell catchup, UI badge)
            SeverActionsNative.Native_SetPackageState(akActor, !isWaiting, false, false)

            ; A re-evaluation mid-sit stands a furniture user up, and the use package
            ; outranks follow anyway: their follow picks up when they stand.
            If !SeverActions_FurnitureLib.IsUsing(akActor)
                akActor.EvaluatePackage()
            EndIf
            Debug.Trace("[SeverActions_Follow] Reapplied companion follow tracking for: " + akActor.GetDisplayName() + " (waiting=" + isWaiting + ")")
        EndIf
        i += 1
    EndWhile
EndFunction

; =============================================================================
; CASUAL FOLLOW — pool-seated (guards, random NPCs, temporary)
; Called by startfollowing.yaml / stopfollowing.yaml
; =============================================================================
; Cancel a journey or wait through the travelcore provider
; (SeverActions_ModuleBase.CallBool("travelcore", "cancelJourney", ...)), never a
; SeverActions_Travel / TravelCore cast: neither is in followers' closure (DR2),
; and a journey can run without the travel module.

Function SetFollowDistance(Actor akActor, String distance)
    {Per-follower trailing distance. "close"/"near"/"tight" adds
     CloseFollowFaction, which gates SeverActions_FollowPlayerClose (~150-200u)
     above the standard package (~500-600u) on every follow alias; anything
     else removes it. The faction persists in the save, so the choice survives
     reload and dismiss/re-recruit. Called by the UI's setFollowDistance verb.}
    if !akActor
        return
    endif
    Faction closeFac = Game.GetFormFromFile(0x16567B, "SeverActions.esp") as Faction
    if !closeFac
        Debug.Trace("[SeverActions_Follow] SetFollowDistance: CloseFollowFaction missing (old ESP?)")
        return
    endif
    String d = SeverActionsNative.StringToLower(distance)
    Bool wantClose = StringUtil.Find(d, "close") >= 0 || StringUtil.Find(d, "near") >= 0 || StringUtil.Find(d, "tight") >= 0
    if wantClose
        if !akActor.IsInFaction(closeFac)
            akActor.AddToFaction(closeFac)
        endif
        SkyrimNetApi.RegisterEvent("follow_distance", \
            akActor.GetDisplayName() + " will now stay close at " + Game.GetPlayer().GetDisplayName() + "'s side while following.", akActor, None)
        Debug.Notification(SeverActionsNativeExt2.Native_L10nFmt("follow.willFollowClose", ("" + akActor.GetDisplayName())))
    else
        if akActor.IsInFaction(closeFac)
            akActor.RemoveFromFaction(closeFac)
        endif
        SkyrimNetApi.RegisterEvent("follow_distance", \
            akActor.GetDisplayName() + " will now follow at a normal distance, giving " + Game.GetPlayer().GetDisplayName() + " room.", akActor, None)
        Debug.Notification(SeverActionsNativeExt2.Native_L10nFmt("follow.willFollowAtNormal", ("" + akActor.GetDisplayName())))
    endif
    akActor.EvaluatePackage()
    Debug.Trace("[SeverActions_Follow] SetFollowDistance: " + akActor.GetDisplayName() + " close=" + wantClose)
EndFunction

Function StartFollowing(Actor akActor)
    {Temporary (casual) follow for any NPC, with no roster entry: a follow-pool
     seat plus the FollowerFollowKW LinkedRef, the same mechanism as companions.}
    if !akActor || akActor.IsDead()
        return
    endif

    ; The Final Audit is unrecruitable by design (same guard as RegisterFollower).
    if SeverActionsNativeExt2.Venture_Audit_IsCollector(akActor)
        SkyrimNetApi.RegisterEvent("follower_recruit_failed",             akActor.GetDisplayName() + " serves the Imperial Treasury alone - the Final Audit follows no one. Whatever business " + Game.GetPlayer().GetDisplayName() + " has with them can be conducted right where they stand.",             akActor, None)
        return
    endif

    SeverActions_FollowerManager fmTO = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager

    ; Hands off: another framework owns them, or Tracking mode, where SA leads
    ; nobody (D45). Never register our package or set hasFollowPkg on them (the
    ; flag re-enables the native follow monitors). The Tracking-only case must
    ; say so (notification below): a silent return leaves the wheel's follow
    ; button doing nothing.
    If SeverActions_ModuleBase.IsFollowHandsOff(akActor)
        ; Take no ownership, but release what SA holds: its sandbox overrides
        ; outrank the owner's follow package and the waiting faction still reads
        ; as waiting (see ClearWaitingFaction), so the NPC would stay put.
        fmTO.StripSandboxesForFollow(akActor)
        fmTO.ClearWorkSandboxForFollow(akActor)
        ClearWaitingFaction(akActor)
        ; End any journey or wait too (0.0: no follower restore, the owner drives them).
        SeverActions_ModuleBase.CallBool("travelcore", "cancelJourney", akActor, None, "", 0.0)
        If SeverActionsNativeExt2.Native_IsNFFInstalled() && SeverActions_NFFLib.NFFResume(akActor)
            ; NFF owns them and has its own wait state - release it there, or a
            ; follower the player parked through us could never be un-parked.
            Debug.Trace("[SeverActions_Follow] StartFollowing: released " + akActor.GetDisplayName() + " through NFF")
        Else
            akActor.SetAV("WaitingForPlayer", 0)
            akActor.EvaluatePackage()
            If SeverActionsNativeExt2.Native_IsTrackOnlyFollower(akActor)
                Debug.Trace("[SeverActions_Follow] StartFollowing: " + akActor.GetDisplayName() + " is track-only - deferred to their own framework")
            Else
                ; Nobody owns them, so this is Tracking mode (D45): say so.
                Debug.Notification(SeverActionsNativeExt2.Native_L10nFmt("follow.trackingModeDoesNotDrive", ("" + akActor.GetDisplayName())))
                Debug.Trace("[SeverActions_Follow] StartFollowing: Tracking mode - SA leads nobody, " + akActor.GetDisplayName() + " stays put (D45)")
            EndIf
        EndIf
        Return
    EndIf

    ; Tell listeners the player called this actor over (e.g. Hearth releases a
    ; camp-pinned follower); strArg is the verb. A ModEvent delivers exactly the
    ; pushed args, so push all four in the handler's order: eventName, strArg,
    ; numArg, sender.
    int followEvt = ModEvent.Create("SeverActions_FollowerCalledByPlayer")
    if followEvt
        ModEvent.PushString(followEvt, "SeverActions_FollowerCalledByPlayer")
        ModEvent.PushString(followEvt, "follow")
        ModEvent.PushFloat(followEvt, 0.0)
        ModEvent.PushForm(followEvt, akActor)
        ModEvent.Send(followEvt)
    endif

    ; End any journey or wait, so its arrival override (e.g. Hearth's
    ; CampSandboxPackage) can't outrank the follow below. 0.0 = no follower
    ; restore (we apply follow ourselves); a no-op when not traveling.
    SeverActions_ModuleBase.CallBool("travelcore", "cancelJourney", akActor, None, "", 0.0)

    ; Clear WaitingForPlayer FIRST: the follow packages gate on it == 0, and in
    ; the gap before follow applies the engine creates an FF-prefix runtime sandbox.
    akActor.SetAV("WaitingForPlayer", 0)

    ; Leave a safe-interior auto-sandbox (priority 100 outranks the pool's 95)
    ; and teleport to the player; a no-op unless flagged.
    ExitSafeInteriorSandbox(akActor)

    ; Not gated on IsSandboxing: if the flag was lost (save/load, timing) a gated
    ; removal would leave the override on forever. No-ops when nothing is active.
    SetSandboxFlag(akActor, false)
    SeverActionsNative.UnregisterSandboxUser(akActor)
    RemoveWaitSandboxPackages(akActor)

    ; Drop the work-sandbox override (110) so it can't outrank the pool follow
    ; (95), as recruit does. The work assignment stays: the schedule gates on
    ; ActivelyFollowing and re-applies work once StopFollowing clears it.
    SeverActions_FollowerManager fmWork = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
    if fmWork
        fmWork.ClearWorkSandboxForFollow(akActor)
        ; Home / play / furniture / safe-interior sandboxes go too.
        fmWork.StripSandboxesForFollow(akActor)
    endif

    If SeverActions_WaitingFaction
        ClearWaitingFaction(akActor)
    EndIf

    ; Seat in the pool: its alias packages re-apply on cell load, while a
    ; SkyrimNet FollowPlayer override stops being served past a load door. No
    ; RegisterPackage: one mechanism drives follow, or the AI flickers.
    If SeverActions_FollowerFollowKW
        SeverActionsNative.LinkedRef_Set(akActor, Game.GetPlayer(), SeverActions_FollowerFollowKW)
    Else
        Debug.Trace("[SeverActions_Follow] WARNING: FollowerFollowKW not set!")
    EndIf
    AssignFollowerSlot(akActor)
    ; Register with OrphanCleanup: with the scanner on (orphanCleanupEnabled) it
    ; strips an unregistered holder's LinkedRef (its registry clears on load;
    ; VerifyCasualFollowPackages re-registers seated casuals).
    SeverActionsNative.OrphanCleanup_RegisterFollower(akActor)
    SeverActionsNative.Native_SetPackageState(akActor, true, false, false)
    akActor.EvaluatePackage()

    ; ENGAGED tag in prompts.
    SetActivelyFollowing(akActor, true)

    Debug.Notification(SeverActionsNativeExt2.Native_L10nFmt("follow.isNowFollowingYou", ("" + akActor.GetDisplayName())))
EndFunction

Function StopFollowing(Actor akActor)
    {Stop casual following: free the pool seat and LinkedRef, and any legacy
     SkyrimNet FollowPlayer registration.}
    if !akActor
        return
    endif

    ; Sandbox teardown, ungated.
    SetSandboxFlag(akActor, false)
    SeverActionsNative.UnregisterSandboxUser(akActor)
    RemoveWaitSandboxPackages(akActor)

    ; Never a registered companion's seat: CompanionStopFollowing owns theirs,
    ; and the LLM can fire this verb at anyone.
    If !SeverActionsNativeExt.Native_GetIsFollower(akActor)
        ClearFollowerSlot(akActor)
        SeverActionsNative.OrphanCleanup_UnregisterFollower(akActor)
        If SeverActions_FollowerFollowKW
            SeverActionsNative.LinkedRef_Clear(akActor, SeverActions_FollowerFollowKW)
        EndIf
    EndIf
    ; A legacy casual's SkyrimNet FollowPlayer (a no-op otherwise; SkyrimNet
    ; re-evaluates the package itself).
    SkyrimNetApi.UnregisterPackage(akActor, "FollowPlayer")
    SeverActionsNative.Native_SetPackageState(akActor, false, false, false)

    SetActivelyFollowing(akActor, false)

    ; Refill a dismissed/homed NPC's schedule alias (no-op if they re-follow).
    SeverActions_FollowerManager fmStop = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
    If fmStop
        fmStop.RefillSchedAliasesAfterStop(akActor)
    EndIf

    Debug.Notification(SeverActionsNativeExt2.Native_L10nFmt("follow.stoppedFollowingYou", ("" + akActor.GetDisplayName())))
    ; A state line, not history (see RegisterFollowStateEvent). A companion
    ; really walking out is followerleaves.yaml's persistent follower_left_voluntarily.
    RegisterFollowStateEvent(akActor, "follower_left", \
        akActor.GetDisplayName() + " stopped following " + Game.GetPlayer().GetDisplayName())
EndFunction

; =============================================================================
; COMPANION FOLLOW (roster companions; called by FollowerManager)
; =============================================================================

Function CompanionStartFollowing(Actor akActor)
    {Start a roster companion following: the LinkedRef to the player plus a
     follow-pool seat, whose alias packages apply at once.}
    if !akActor || akActor.IsDead()
        return
    endif

    ; WaitingForPlayer FIRST, before the sandbox comes off (see StartFollowing).
    akActor.SetAV("WaitingForPlayer", 0)
    ; Drop the waiting faction Sandbox() added, or prompt selectors read a
    ; following companion as waiting.
    If SeverActions_WaitingFaction
        ClearWaitingFaction(akActor)
    EndIf

    ; Now the sandbox can come off: follow is already eligible.
    SetSandboxFlag(akActor, false)
    SeverActionsNative.UnregisterSandboxUser(akActor)
    RemoveWaitSandboxPackages(akActor)

    ; A stale casual FollowPlayer registration (defensive).
    SkyrimNetApi.UnregisterPackage(akActor, "FollowPlayer")

    If SeverActions_FollowerFollowKW
        SeverActionsNative.LinkedRef_Set(akActor, Game.GetPlayer(), SeverActions_FollowerFollowKW)
    Else
        Debug.Trace("[SeverActions_Follow] WARNING: FollowerFollowKW not set!")
    EndIf

    ; A followed companion holds no schedule aliases (no-op pre-migration).
    SeverActions_FollowerManager fmSched = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
    If fmSched
        fmSched.EmptySchedAliasesForFollow(akActor)
    EndIf

    ; The alias packages apply now and re-apply on cell load. No RegisterPackage.
    AssignFollowerSlot(akActor)

    SetActivelyFollowing(akActor, true)

    ; hasFollowPkg: SA drives this follow (drift monitor, cell catch-up, UI badge).
    SeverActionsNative.Native_SetPackageState(akActor, true, false, false)

    ; See StartFollowing.
    SeverActionsNative.OrphanCleanup_RegisterFollower(akActor)

    akActor.EvaluatePackage()
EndFunction

Function CompanionStopFollowing(Actor akActor, Bool evaluateAfter = true)
    {Stop companion following: free the pool seat (its packages go with it)
     and every tracked LinkedRef. Pass evaluateAfter=false when the caller
     applies a new package right after (dismiss -> SendHome): an evaluate with
     no package creates an FF-prefix fallback.}
    if !akActor
        return
    endif

    ; Sandbox teardown, ungated.
    SetSandboxFlag(akActor, false)
    SeverActionsNative.UnregisterSandboxUser(akActor)
    RemoveWaitSandboxPackages(akActor)

    ClearFollowerSlot(akActor)

    SeverActionsNative.OrphanCleanup_UnregisterFollower(akActor)

    ; ALL tracked LinkedRefs, not just follow: travel, furniture or arrest refs an
    ; interrupted system left would stay in the cosave and restore on load. Each
    ; system still clears its own on completion; this is the final sweep.
    SeverActionsNative.LinkedRef_ClearAll(akActor)
    If SeverActions_WaitingFaction
        ClearWaitingFaction(akActor)
    EndIf

    ; A leftover casual FollowPlayer registration.
    SkyrimNetApi.UnregisterPackage(akActor, "FollowPlayer")

    SetActivelyFollowing(akActor, false)

    ; hasFollowPkg off (see CompanionStartFollowing).
    SeverActionsNative.Native_SetPackageState(akActor, false, false, false)

    ; Refill a dismissed/homed NPC's schedule alias (no-op when the caller
    ; re-follows or waits them).
    SeverActions_FollowerManager fmSchedStop = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
    If fmSchedStop
        fmSchedStop.RefillSchedAliasesAfterStop(akActor)
    EndIf

    If evaluateAfter
        akActor.EvaluatePackage()
    EndIf
EndFunction

; =============================================================================
; MANUAL WAIT SANDBOX (casual and companion follow)
; =============================================================================

Function Sandbox(Actor akActor)
    if !akActor || akActor.IsDead()
        return
    endif

    if !SandboxPackage
        Debug.Trace("[SeverActions_Follow] Sandbox: No SandboxPackage assigned!")
        return
    endif

    ; Apply the wait package FIRST: setting WaitingForPlayer first drops the
    ; follow package, and the engine fills the gap with an FF-prefix sandbox.
    ; Flags 0 skips the AI reset. GetWaitSandboxPackage picks Wait In Place or
    ; the wide sandbox.
    Package waitPkg = GetWaitSandboxPackage()
    ActorUtil.AddPackageOverride(akActor, waitPkg, SandboxPackagePriority, 0)

    ; Now the follow can drop: the sandbox already covers them.
    SkyrimNetApi.UnregisterPackage(akActor, "FollowPlayer")
    akActor.SetAV("WaitingForPlayer", 1)

    ; After the WaitingForPlayer write, which is what stops SituationMonitor claiming
    ; them again: a safe-interior relax gives way to this wait.
    YieldSafeInteriorToWait(akActor, waitPkg)

    ; Re-evaluate now: the next vanilla tick can be seconds away, and until then
    ; they keep trailing the player.
    akActor.EvaluatePackage()

    ; Keep hasFollowPkg (no Native_SetPackageState(false)): StopSandbox reads it
    ; to tell SA-managed from track-only. SandboxManager's teleport skips this
    ; actor through isSandboxing, set here (see SANDBOX STATE HELPERS).
    SetSandboxFlag(akActor, true)

    ; Release schedule aliases so the schedule can't pull them away mid-wait.
    SeverActions_FollowerManager fmSchedSbx = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
    If fmSchedSbx
        fmSchedSbx.EmptySchedAliasesForFollow(akActor)
    EndIf

    ; No SandboxManager registration: a wait holds until the player resumes
    ; them (StopSandbox).

    SetActivelyFollowing(akActor, false)

    ; Interop signal (see SeverActions_WaitingFaction).
    If SeverActions_WaitingFaction
        akActor.AddToFaction(SeverActions_WaitingFaction)
    EndIf

    RegisterFollowStateEvent(akActor, "follower_relaxing", akActor.GetDisplayName() + " decides to relax and wander around the area.")
EndFunction

Function StopSandbox(Actor akActor)
    if !akActor
        return
    endif

    ; Snapshot before teardown: CompanionWait's track-only recovery calls this
    ; defensively, and the "stopped relaxing" feedback at the end must only
    ; follow a real sandbox.
    Bool wasSandboxing = IsSandboxing(akActor)

    ; WaitingForPlayer FIRST, before the sandbox comes off (see StartFollowing).
    akActor.SetAV("WaitingForPlayer", 0)

    SetSandboxFlag(akActor, false)

    If SeverActions_WaitingFaction
        ClearWaitingFaction(akActor)
    EndIf

    SeverActionsNative.UnregisterSandboxUser(akActor)

    ; Both wait variants (see RemoveWaitSandboxPackages).
    RemoveWaitSandboxPackages(akActor)

    ; Re-register FollowPlayer only for a legacy casual SA drives:
    ;   1. IsInFollowerSlot (companions, pool casuals, overflow): their follow
    ;      package re-asserts once WaitingForPlayer clears; FollowPlayer on top
    ;      flickers the AI.
    ;   2. Legacy SkyrimNet casuals (hasFollowPkg, not seated): want it back.
    ;   3. Track-only followers from CompanionWait's recovery (hasFollowPkg
    ;      false): their own mod drives them, and a FollowPlayer here suppressed
    ;      it and left them standing.
    Bool isSAManaged = SeverActionsNative.Native_GetHasFollowPkg(akActor)
    If !IsInFollowerSlot(akActor) && isSAManaged
        SkyrimNetApi.RegisterPackage(akActor, "FollowPlayer", FollowPackagePriority, 0, true)
    EndIf

    ; Re-evaluate now, as in Sandbox (RegisterPackage above is async).
    akActor.EvaluatePackage()

    ; Only when a follow exists to resume: on a dismissed/homed NPC a stale
    ; ActivelyFollowing silently freezes their work schedule.
    If IsInFollowerSlot(akActor) || SkyrimNetApi.HasPackage(akActor, "FollowPlayer")
        SetActivelyFollowing(akActor, true)
    EndIf

    ; Refill a dismissed/homed NPC's schedule alias (no-op when follow resumed).
    SeverActions_FollowerManager fmSchedStopSbx = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_FollowerManager
    If fmSchedStopSbx
        fmSchedStopSbx.RefillSchedAliasesAfterStop(akActor)
    EndIf

    If wasSandboxing
        Debug.Notification(SeverActionsNativeExt2.Native_L10nFmt("follow.stoppedRelaxing", ("" + akActor.GetDisplayName())))
        RegisterFollowStateEvent(akActor, "follower_relax_stopped", akActor.GetDisplayName() + " stops relaxing and is ready to move.")
    EndIf
EndFunction

; =============================================================================
; ELIGIBILITY AND EXTERNAL WAIT
; =============================================================================

; Casual-follow eligibility for FollowerManager's hotkey / wheel follow toggle.

Bool Function StartFollowing_IsEligible(Actor akActor) Global
    if !akActor || akActor.IsDead() || akActor.IsInCombat()
        return false
    endif

    ; Not vanilla followers (CurrentFollowerFaction).
    Faction factionCompanion = Game.GetFormFromFile(0x084D1B, "Skyrim.esm") as Faction
    if factionCompanion && akActor.IsInFaction(factionCompanion)
        return false
    endif

    ; hasPackage: a legacy SkyrimNet casual. isCompanion: IsInFollowerSlot, so
    ; pool casuals count too. Global, so the instance comes from 0x000D62.
    Bool hasPackage = SkyrimNetApi.HasPackage(akActor, "FollowPlayer")
    SeverActions_Follow instance = Game.GetFormFromFile(0x000D62, "SeverActions.esp") as SeverActions_Follow
    Bool isCompanion = instance && instance.IsInFollowerSlot(akActor)
    Bool isWaiting = akActor.GetAV("WaitingForPlayer") > 0
    Bool isSandboxing = SeverActionsNativeExt.Native_GetSandboxing(akActor)

    ; Seated: eligible only while waiting or sandboxing.
    If isCompanion
        return isWaiting || isSandboxing
    EndIf

    ; A legacy casual already following: not eligible.
    if hasPackage && !isWaiting && !isSandboxing
        return false
    endif

    return true
EndFunction

Event OnExternalWaitAdopt(String eventName, String strArg, Float numArg, Form sender)
    {A follower-command mod (Swiftly Order Squad class) parked one of our
     companions with a bare SetAV(WaitingForPlayer, 1). SA's follow packages
     have no wait branch, so they would drop to default AI and walk home:
     apply the real SA wait. FollowDriftMonitor confirms over two scans with a
     60s cooldown per actor; re-validate, as Papyrus may have acted since.}
    Actor akActor = sender as Actor
    If !akActor || akActor.IsDead()
        Return
    EndIf
    If akActor.GetAV("WaitingForPlayer") != 1.0
        Return
    EndIf
    If IsSandboxing(akActor)
        Return
    EndIf
    Debug.Trace("[SeverActions_Follow] Adopting external wait on " + akActor.GetDisplayName() + " (third-party WaitingForPlayer=1)")
    Sandbox(akActor)
EndEvent

; ============================================================================
; SCENE EVENTS
; ============================================================================

Int Property FollowStateTTLMs = 300000 Auto
{How long a follow-state line stays in scene context (ms).}

Function RegisterFollowStateEvent(Actor akActor, String asType, String asText)
    {Following / waiting / relaxing is STATE, not history. Every state line
     shares the eventId follow_state_<fid>, SkyrimNet's REPLACE key, so each
     companion keeps one line saying what they do NOW instead of one per
     transition (the sandbox system flips them constantly).
     FollowerManager.RegisterFollowStateEvent uses the same key; keep the two
     in step. One-off history (a companion walking out, an arrest) stays on
     RegisterEvent / RegisterPersistentEvent.}

    If akActor == None
        Return
    EndIf
    SkyrimNetApi.RegisterShortLivedEvent("follow_state_" + akActor.GetFormID(), \
        asType, asText, "", FollowStateTTLMs, akActor, Game.GetPlayer())
EndFunction

; -----------------------------------------------------------------------------
; Safe-exit stubs (M-I, check 20): removed functions a saved frame may still call by
; name (F7); each answers a safe default. Never remove one (fomod/safe_exit_stubs.json).
; -----------------------------------------------------------------------------

Int Function FindFreeFollowAlias()
    {Safe-exit stub: the 21-slot alias search, replaced by FollowPool_Claim.}
    ; M-I-STUB 3.9.14-beta25 (P3-08): the 21-slot alias search
    Return -1
EndFunction
