// SeverActionsNative - SKSE Plugin with Papyrus Native Functions
// Native SKSE plugin for SeverActions performance optimization - string utilities, database lookups, inventory helpers
// Author: Severause
// Generated by Spooky's AutoMod Toolkit

#include "plugin.h"
#include "papyrus.h"

#include <filesystem>
#include <format>

// Plugin version info for SKSE
SKSEPluginInfo(
    .Version = { 1, 0, 0, 0 },
    .Name = "SeverActionsNative",
    .Author = "Severause",
    .SupportEmail = "",
    .StructCompatibility = SKSE::StructCompatibility::Independent,
    .RuntimeCompatibility = SKSE::VersionIndependence::AddressLibrary,
    .MinimumSKSEVersion = { 2, 0, 0, 0 }
)

static void InitializeLogging()
{
    std::filesystem::path logPath;

    auto skseLogDir = SKSE::log::log_directory();
    if (skseLogDir) {
        logPath = *skseLogDir / PLUGIN_NAME;
        logPath += ".log";
    } else {
        // Fallback: use Data/SKSE/Plugins folder
        logPath = std::filesystem::path("Data/SKSE/Plugins") / PLUGIN_NAME;
        logPath += ".log";
    }

    try {
        auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(logPath.string(), true);
        auto log = std::make_shared<spdlog::logger>("global log", std::move(sink));

        log->set_level(spdlog::level::trace);
        log->flush_on(spdlog::level::trace);

        spdlog::set_default_logger(std::move(log));
        spdlog::set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%l] %v");

        SKSE::log::info("Log initialized at: {}", logPath.string());
    } catch (const std::exception& e) {
        // If all else fails, try to report
        SKSE::stl::report_and_fail(std::format("Failed to create log file: {}", e.what()));
    }
}

SKSEPluginLoad(const SKSE::LoadInterface* a_skse)
{
    InitializeLogging();

    SKSE::log::info("{} v{} loading...", PLUGIN_NAME, PLUGIN_VERSION);

    SKSE::Init(a_skse);

    SKSE::log::info("{} v{} loaded", PLUGIN_NAME, PLUGIN_VERSION);

    // Register Papyrus functions
    auto papyrus = SKSE::GetPapyrusInterface();
    if (papyrus) {
        papyrus->Register(SeverActionsNative::Papyrus::RegisterFunctions);
        SKSE::log::info("Papyrus functions registered");
    }

    // Initialize plugin
    SeverActionsNative::Plugin::Initialize();

    return true;
}
