// SeverActionsNative - Plugin Implementation
// Generated by Spooky's AutoMod Toolkit
//
// Simplified architecture: Native C++ provides fast database lookups and
// workstation finding. YAML actions call Papyrus, which calls native functions.
// No direct SkyrimNet action registration - all execution goes through Papyrus.

#include "plugin.h"
#include "FurnitureManager.h"
#include "SandboxManager.h"
#include "DialogueAnimManager.h"
#include "RecipeDB.h"
#include "AlchemyDB.h"
#include "SurvivalUtils.h"
#include "LocationResolver.h"
#include "ActorFinder.h"
#include "NND_API.h"
#include "DBFBridge.h"
#include "YieldMonitor.h"
#include "TeammateMonitor.h"
#include "OrphanCleanup.h"

namespace SeverActionsNative
{
    void Plugin::Initialize()
    {
        SKSE::log::info("Initializing {}...", PLUGIN_NAME);

        // Register for SKSE messages
        auto messaging = SKSE::GetMessagingInterface();
        if (messaging) {
            messaging->RegisterListener(OnMessage);
        }

        SKSE::log::info("{} initialization complete", PLUGIN_NAME);
    }

    void Plugin::OnMessage(SKSE::MessagingInterface::Message* a_msg)
    {
        switch (a_msg->type) {
        case SKSE::MessagingInterface::kDataLoaded:
        {
            SKSE::log::info("Data loaded — initializing native subsystems...");

            // Event-driven managers (void init — log errors internally)
            FurnitureManager::GetSingleton()->Initialize();
            SandboxManager::GetSingleton()->Initialize();
            DialogueAnimManager::GetSingleton()->Initialize();
            SurvivalUtils::GetSingleton()->Initialize();

            // Database subsystems — check return values
            int failCount = 0;

            SKSE::log::info("Initializing recipe database...");
            if (!RecipeDB::GetInstance().Initialize()) {
                SKSE::log::error("RecipeDB initialization FAILED — cooking/smithing lookups unavailable");
                failCount++;
            }

            SKSE::log::info("Initializing alchemy database...");
            if (!AlchemyDB::GetInstance().Initialize()) {
                SKSE::log::error("AlchemyDB initialization FAILED — potion/poison lookups unavailable");
                failCount++;
            }

            // Void-returning initializers — log before, rely on internal error logging
            SKSE::log::info("Initializing location resolver...");
            LocationResolver::GetInstance().Initialize();

            SKSE::log::info("Initializing actor finder...");
            ActorFinder::GetInstance().Initialize();

            // Optional soft dependency — Dynamic Book Framework bridge
            SKSE::log::info("Initializing DBF bridge...");
            if (DBFBridge::GetInstance().Initialize()) {
                SKSE::log::info("Dynamic Book Framework detected — DBF book content active");
            } else {
                SKSE::log::info("Dynamic Book Framework not detected — standard book text only");
            }

            // Yield hit monitor — tracks hits on surrendered actors
            SKSE::log::info("Initializing yield monitor...");
            YieldMonitor::GetSingleton()->Initialize();

            // Teammate monitor — detects SetPlayerTeammate changes for instant follower onboarding
            SKSE::log::info("Initializing teammate monitor...");
            TeammateMonitor::GetSingleton()->Initialize();

            // Orphan cleanup — detects stale LinkedRef keywords from crashed scripts
            SKSE::log::info("Initializing orphan cleanup...");
            OrphanCleanup::GetSingleton()->Initialize();

            if (failCount > 0) {
                SKSE::log::warn("SeverActionsNative: {} database(s) failed to initialize — some features will be unavailable", failCount);
            } else {
                SKSE::log::info("SeverActionsNative: All subsystems initialized successfully");
            }
            break;
        }

        case SKSE::MessagingInterface::kPostLoad:
        {
            SKSE::log::info("Post load — checking for NPC Names Distributor...");
            auto* nndAPI = reinterpret_cast<NND_API::IVNND1*>(
                NND_API::RequestPluginAPI(NND_API::InterfaceVersion::kV2)
            );
            if (nndAPI) {
                ActorFinder::GetInstance().SetNNDAPI(nndAPI);
                SKSE::log::info("NPC Names Distributor API acquired — custom NPC names will be searchable");
            } else {
                SKSE::log::info("NPC Names Distributor not detected — using base game names only");
            }
            break;
        }

        case SKSE::MessagingInterface::kPostLoadGame:
        case SKSE::MessagingInterface::kNewGame:
            SKSE::log::info("Game loaded - running post-load rescan for unmapped NPCs...");
            ActorFinder::GetInstance().PostLoadRescan();

            // Reset teammate tracking — Papyrus side will re-detect via Maintenance()
            // This prevents stale FormIDs from a previous save from blocking detection
            TeammateMonitor::GetSingleton()->ClearTracking();

            // Reset orphan tracking — Papyrus will re-register active travelers/followers
            OrphanCleanup::GetSingleton()->ClearTracking();

            SKSE::log::info("Game loaded - native databases ready for Papyrus queries");
            break;
        }
    }
}
